let days=prompt("entre un nombre entre 1 et 7 :")

if(days == 1)
{
    alert("lundi");
}
else if (days == 2)
{
    alert("mardi");
}
else if (days == 3)
{
    alert("mercredi");
}
else if (days == 4)
{
    alert("jeudi");
}
else if (days == 5)
{
    alert("vendredi");
}
else if (days == 6)
{
    alert("samedi");
}
else if (days ==7 )
{
    alert("dimanche");
}
else
{ alert("invalide numbre");
}